### ISSUE TITLE
Implement PVThumbView

### ISSUE THREAD

**Issue by tjweir** [enormego/PhotoViewer#1]
(Trying not to be an ass about this, just a request)

I'm not sure if you have the code lying about, but I'd love to have your implementation of PVThumbView.

**Comment by henrik** [comment]
I have a thumb view in my fork: http://github.com/henrik/PhotoViewer

**Comment by Stokestack** [comment]
Nice work!  I do encounter a problem with rotation, though: The top row of thumbnails is up under the nav bar after rotating.  If you then view an individual picture and come back to the thumbnails, the layout is corrected.

I tried adding a call to setNeedsLayout after rotation, but it doesn't do anything.

**Comment by Gilmargolin** [comment]
can you help me with finding a way to put an overlay on top of an image i can't figure out what method i should add the UIImageView to.
