### ISSUE TITLE
info.plist settings to run on ipod touch

### ISSUE THREAD

**Issue by brynjar** [enormego/PhotoViewer#9]
Hi,
it seems that in order for universal apps to build for iphone, ipod touch and ipad you need the following info.plist settings:

Main nib file base name -> MainWindow-iphone
Main nib file base name (ipad) -> MainWindow-ipad

Using

Main nib file base name (iphone) -> MainWindow-iphone
Main nib file base name (ipad) -> MainWindow-ipad

doesn't allow the app to run properly on ipod touch...

**Comment by devindoty** [comment]
The base nib name should be MainWindow, as iPhone and iPod are considered the same. iPad nib should be MainWindow-ipad.

**Comment by brynjar** [comment]
Sorry,
what I meant specifically was that in the PhotoViewer code I downloaded yesterday, the sample project info.plist is setup such that it won't work on ipod touch - but the changes I list above fix it.

**Comment by devindoty** [comment]
Ah OK, thanks!
